name: paint-dream

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - C:/Home/Volumes/PaintDream/db:/var/lib/postgresql/data
  backend:
    image: backend
    build:
      context: ./PaintDreamBackend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - Kestrel__Endpoints__Http__Url=http://+:5000
      - ConnectionStrings__PaintDream=Host=db;Port=5432;Database=PaintDream;Username=admin;Password=admin
    depends_on:
      - db
  envoy:
    image: envoy
    build:
      context: ./paint-dream-envoy
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "9901:9901"