// @generated by protobuf-ts 2.9.3
// @generated from protobuf file "pixel_info.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PixelInfo } from "./pixel_info";
import type { FullPixelInfosDto } from "./pixel_info";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { CreatePixelInfosDto } from "./pixel_info";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { PixelInfoHistoriesDto } from "./pixel_info";
import type { Empty } from "./google/protobuf/empty";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service PixelInfo
 */
export interface IPixelInfoClient {
    /**
     * @generated from protobuf rpc: GetPixelInfoHistories(google.protobuf.Empty) returns (PixelInfoHistoriesDto);
     */
    getPixelInfoHistories(input: Empty, options?: RpcOptions): UnaryCall<Empty, PixelInfoHistoriesDto>;
    /**
     * @generated from protobuf rpc: CreatePixelInfos(CreatePixelInfosDto) returns (google.protobuf.Empty);
     */
    createPixelInfos(input: CreatePixelInfosDto, options?: RpcOptions): UnaryCall<CreatePixelInfosDto, Empty>;
    /**
     * @generated from protobuf rpc: SubscribePixelInfosUpdates(google.protobuf.Empty) returns (stream FullPixelInfosDto);
     */
    subscribePixelInfosUpdates(input: Empty, options?: RpcOptions): ServerStreamingCall<Empty, FullPixelInfosDto>;
}
/**
 * @generated from protobuf service PixelInfo
 */
export class PixelInfoClient implements IPixelInfoClient, ServiceInfo {
    typeName = PixelInfo.typeName;
    methods = PixelInfo.methods;
    options = PixelInfo.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetPixelInfoHistories(google.protobuf.Empty) returns (PixelInfoHistoriesDto);
     */
    getPixelInfoHistories(input: Empty, options?: RpcOptions): UnaryCall<Empty, PixelInfoHistoriesDto> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, PixelInfoHistoriesDto>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreatePixelInfos(CreatePixelInfosDto) returns (google.protobuf.Empty);
     */
    createPixelInfos(input: CreatePixelInfosDto, options?: RpcOptions): UnaryCall<CreatePixelInfosDto, Empty> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePixelInfosDto, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SubscribePixelInfosUpdates(google.protobuf.Empty) returns (stream FullPixelInfosDto);
     */
    subscribePixelInfosUpdates(input: Empty, options?: RpcOptions): ServerStreamingCall<Empty, FullPixelInfosDto> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, FullPixelInfosDto>("serverStreaming", this._transport, method, opt, input);
    }
}
